# API Base URL Configuration - CHANGE THIS TO YOUR SERVER URL
@baseUrl = http://your-server-ip:5000

###
# Testing
GET https://api.rajaongkir.com/starter/province
Content-Type: application/json
key: b89677246deb9ff63f38d89f32ab7b7

###
# Login Admin
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "dandigeming85@gmail.com",
    "password": "123"
}

###Update Category
PATCH {{baseUrl}}/api/product/category/update-category/a7477245-3c54-4d14-a2b7-7cd7711557eb
Content-Type: application/json

{
    "name": "Fashion Wanita category updated",
    "description": "Tren Fashion Terkini Untuk Wanita, Dengan Pilihan Busana Untuk Segala Keperluan, Termasuk Pakaian Kasual, Formal, Dan Pesta. updated"
}
###

###
# get data user
GET {{baseUrl}}/api/destinations

###
# logout
DELETE {{baseUrl}}/delete-category/002bdd07-78dc-40ca-9991-c2799fd42aa8

###
# logout
DELETE {{baseUrl}}/logout
###
# logout
GET {{baseUrl}}/me

###
POST {{baseUrl}}/add-category
Content-Type: application/json

{
    "name":"product 2",
    "description": "Test"
}
###
GET {{baseUrl}}/get-category-management-data